DROP TABLE IF EXISTS STUDIES;
DROP TABLE IF EXISTS LEVELS;
DROP TABLE IF EXISTS NODES;

CREATE TABLE STUDIES (
    study_id INTEGER PRIMARY KEY AUTOINCREMENT,
    study_name TEXT UNIQUE NOT NULL,
    study_p REAL NOT NULL,
    study_primary_q TEXT NULL,
    node_id INTEGER NOT NULL,
    FOREIGN KEY (node_id) REFERENCES NODES (node_id)
);

CREATE TABLE LEVELS (
    level_id INTEGER PRIMARY KEY AUTOINCREMENT,
    level_scna TEXT NULL,
    level_scnb TEXT NULL,
    study_id INTEGER NOT NULL,
    FOREIGN KEY (study_id) REFERENCES STUDIES (study_id)
);

CREATE TABLE NODES (
    node_id INTEGER PRIMARY KEY AUTOINCREMENT,
    node_a INTEGER NULL,
    node_b INTEGER NULL,
    node_count INTEGER NOT NULL
);